#####################################################
#                                                   #
#        dnscrypt-proxy configuration               #
#        by t.me/roman_sv in t.me/immalware_chat    #
#        provided in sevcator repository            #
#                                                   #
#####################################################

##################################
#         Global settings        #
##################################

server_names = ['cloudflare', 'cloudflare-ipv6']

listen_addresses = ['127.0.0.1:53', '[::1]:53']

max_clients = 250

ipv4_servers = true
ipv6_servers = true
dnscrypt_servers = true
doh_servers = true
odoh_servers = true

require_dnssec = true
require_nolog = true
require_nofilter = true
disabled_server_names = []

force_tcp = false
http3 = true

timeout = 2500
keepalive = 30

blocked_query_response = 'refused'
lb_strategy = 'first'
lb_estimator = false
log_level = 0
log_file_latest = false
use_syslog = false
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

cert_refresh_delay = 240

bootstrap_resolvers = ['1.1.1.1:53', '9.9.9.11:53']
ignore_system_dns = true
netprobe_timeout = 0
netprobe_address = '1.1.1.1:53'

#########################
#        Filters        #
#########################

block_ipv6 = false
block_unqualified = true
block_undelegated = true
reject_ttl = 10

###########################
#        DNS cache        #
###########################

cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

[broken_implementations]
fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'cisco-sandbox', 'cleanbrowsing-adult', 'cleanbrowsing-adult-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-security', 'cleanbrowsing-security-ipv6']

[anonymized_dns]
skip_incompatible = false

[static.'cloudflare']
stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEABzEuMC4wLjEKL2Rucy1xdWVyeQ'
[static.'cloudflare-ipv6']
stamp = 'sdns://AgcAAAAAAAAAFlsyNjA2OjQ3MDA6OjY4MTA6ZjhmOV0AEmNsb3VkZmxhcmUtZG5zLmNvbQovZG5zLXF1ZXJ5'
