name: Scheduled Build

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1
          check-latest: true
        id: go

      - name: Build
        run: |
          git clone https://github.com/DNSCrypt/dnscrypt-proxy
          chmod +x .github/build.sh
          bash .github/build.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'actions'
          git config --global user.email 'actions@github.com'
          git add -f dnscrypt-proxy/dnscrypt-proxy.exe
          current_date=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "⚡ Updated at ${current_date}" || echo "No changes to commit"
          git push
