name: Scheduled Build

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          repository: DNSCrypt/dnscrypt-proxy
          path: dnscrypt-proxy
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1
          check-latest: true
        id: go

      - name: Build
        run: |
          echo '#!/bin/sh' > ci_build.sh
          echo 'PACKAGE_VERSION="$1"' >> ci_build.sh
          echo 'cd dnscrypt-proxy || exit 1' >> ci_build.sh
          echo 'go clean' >> ci_build.sh
          echo 'env GOOS=windows GOARCH=amd64 go build -mod vendor -ldflags="-s -w"' >> ci_build.sh
          chmod +x ci_build.sh
          bash ci_build.sh
          rm -rf .github

  upload:
    name: Upload to main branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commit and push changes
        run: |
          git config --global user.name 'actions'
          git config --global user.email 'actions@github.com'
          git add -f dnscrypt-proxy/dnscrypt-proxy.exe
          current_date=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "⚡ Updated at ${current_date}" || echo "No changes to commit"
          git push
